volumes:
  prometheus_data: {}
  prom-setup-grafana-storage: {}

services:

  prometheus:
    build: ./prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=15d'
    ports:
      - '9090:9090'
    networks:
      - monitoring
    container_name: prom-setup-prometheus

  blackbox:
    build: ./blackbox
    volumes:
      - ./blackbox/blackbox.yml:/etc/blackbox/blackbox.yml
    command:
      - '--config.file=/etc/blackbox/blackbox.yml'
    ports:
      - '9115:9115'
    networks:
      - monitoring
    container_name: prom-setup-blackbox

  grafana:
    image: grafana/grafana:latest
    container_name: prom-setup-grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - prom-setup-grafana-storage:/var/lib/grafana
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - monitoring
    restart: always

  nginx:
    image: nginx:latest
    container_name: prom-setup-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - grafana
    networks:
      - monitoring
    restart: always

  certgen:
    image: alpine:latest
    container_name: prom-setup-certgen
    volumes:
      - ./nginx/certs:/etc/nginx/certs
    command: >
      /bin/sh -c "
      apk add --no-cache openssl &&
      openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
      -keyout /etc/nginx/certs/grafana.key \
      -out /etc/nginx/certs/grafana.crt \
      -subj '/CN=localhost';
      exit 0;
      "

networks:
  monitoring:
    driver: bridge