global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'blackbox_https'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://www.example.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: instance
        replacement: example.com
      - target_label: __address__
        replacement: blackbox_exporter:9115
