apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-tls
  namespace: default
spec:
  dnsNames:
  - localhost
  secretName: grafana-tls
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer