apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: prom-setup-monitoring
  labels:
    grafana_datasource: "1"
data:
  prometheus-datasource.yml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-service.prom-setup-monitoring.svc.cluster.local:9090
        isDefault: true